package mt

// Country 国家/地区
type Country string

// 国家/地区
const (
	CountrySweden                          Country = "1"   // Sweden
	CountryUnitedStatesOfAmerica           Country = "2"   // United States of America
	CountryRussia                          Country = "3"   // Russia
	CountryFinland                         Country = "4"   // Finland
	CountryCanada                          Country = "5"   // Canada
	CountryFrance                          Country = "6"   // France
	CountryGermany                         Country = "7"   // Germany
	CountryChina                           Country = "8"   // 中国
	CountryItaly                           Country = "9"   // Italy
	CountryDenmark                         Country = "10"  // Denmark
	CountryNorway                          Country = "11"  // Norway
	CountryUnitedKingdom                   Country = "12"  // United Kingdom
	CountryIreland                         Country = "13"  // Ireland
	CountryPoland                          Country = "14"  // Poland
	CountryNetherlands                     Country = "15"  // Netherlands
	CountryBelgium                         Country = "16"  // Belgium
	CountryJapan                           Country = "17"  // Japan
	CountryBrazil                          Country = "18"  // Brazil
	CountryArgentina                       Country = "19"  // Argentina
	CountryAustralia                       Country = "20"  // Australia
	CountryNewZealand                      Country = "21"  // New Zealand
	CountrySpain                           Country = "23"  // Spain
	CountryPortugal                        Country = "24"  // Portugal
	CountryMexico                          Country = "25"  // Mexico
	CountrySingapore                       Country = "26"  // Singapore
	CountrySouthAfrica                     Country = "29"  // South Africa
	CountrySouthKorea                      Country = "30"  // South Korea
	CountryJamaica                         Country = "31"  // Jamaica
	CountryLuxembourg                      Country = "32"  // Luxembourg
	CountryBelize                          Country = "34"  // Belize
	CountryAlgeria                         Country = "35"  // Algeria
	CountryAngola                          Country = "36"  // Angola
	CountryAustria                         Country = "37"  // Austria
	CountryYugoslavia                      Country = "38"  // Yugoslavia
	CountryWesternSamoa                    Country = "39"  // Western Samoa
	CountryMalaysia                        Country = "40"  // Malaysia
	CountryDominicanRepublic               Country = "41"  // Dominican Republic
	CountryGreece                          Country = "42"  // Greece
	CountryGuatemala                       Country = "43"  // Guatemala
	CountryIsrael                          Country = "44"  // Israel
	CountryPakistan                        Country = "45"  // Pakistan
	CountryCzechRepublic                   Country = "46"  // Czech Republic
	CountrySerbia                          Country = "47"  // Serbia
	CountrySeychelles                      Country = "48"  // Seychelles
	CountryPuertoRico                      Country = "50"  // Puerto Rico
	CountryChile                           Country = "51"  // Chile
	CountryCuba                            Country = "52"  // Cuba
	CountryCongo                           Country = "53"  // Congo
	CountryAfghanistan                     Country = "54"  // Afghanistan
	CountryTurkey                          Country = "55"  // Turkey
	CountryUzbekistan                      Country = "56"  // Uzbekistan
	CountrySwitzerland                     Country = "57"  // Switzerland
	CountryKiribati                        Country = "58"  // Kiribati
	CountryPhilippines                     Country = "59"  // Philippines
	CountryBurkinaFaso                     Country = "60"  // Burkina Faso
	CountryNigeria                         Country = "61"  // Nigeria
	CountryIceland                         Country = "62"  // Iceland
	CountryNauru                           Country = "63"  // Nauru
	CountrySlovenia                        Country = "64"  // Slovenia
	CountryAlbania                         Country = "65"  // Albania
	CountryTurkmenistan                    Country = "66"  // Turkmenistan
	CountryBosniaHerzegovina               Country = "67"  // Bosnia Herzegovina
	CountryAndorra                         Country = "68"  // Andorra
	CountryLithuania                       Country = "69"  // Lithuania
	CountryIndia                           Country = "70"  // India
	CountryNetherlandsAntilles             Country = "71"  // Netherlands Antilles
	CountryUkraine                         Country = "72"  // Ukraine
	CountryVenezuela                       Country = "73"  // Venezuela
	CountryHungary                         Country = "74"  // Hungary
	CountryRomania                         Country = "75"  // Romania
	CountryVanuatu                         Country = "76"  // Vanuatu
	CountryVietnam                         Country = "77"  // Vietnam
	CountryTrinidadTobago                  Country = "78"  // Trinidad & Tobago
	CountryHonduras                        Country = "79"  // Honduras
	CountryKyrgyzstan                      Country = "80"  // Kyrgyzstan
	CountryEcuador                         Country = "81"  // Ecuador
	CountryBahamas                         Country = "82"  // Bahamas
	CountryPeru                            Country = "83"  // Peru
	CountryCambodia                        Country = "84"  // Cambodia
	CountryBarbados                        Country = "85"  // Barbados
	CountryBangladesh                      Country = "86"  // Bangladesh
	CountryLaos                            Country = "87"  // Laos
	CountryUruguay                         Country = "88"  // Uruguay
	CountryAntiguaBarbuda                  Country = "89"  // Antigua Barbuda
	CountryParaguay                        Country = "90"  // Paraguay
	CountryUnionOfSovietSocialistRepublics Country = "92"  // Union of Soviet Socialist Republics
	CountryThailand                        Country = "93"  // Thailand
	CountrySenegal                         Country = "94"  // Senegal
	CountryTogo                            Country = "95"  // Togo
	CountryNorthKorea                      Country = "96"  // North Korea
	CountryCroatia                         Country = "97"  // Croatia
	CountryEstonia                         Country = "98"  // Estonia
	CountryColombia                        Country = "99"  // Colombia
	CountryLebanon                         Country = "100" // Lebanon
	CountryLatvia                          Country = "101" // Latvia
	CountryCostaRica                       Country = "102" // Costa Rica
	CountryEgypt                           Country = "103" // Egypt
	CountryBulgaria                        Country = "104" // Bulgaria
	CountryIslaDeMuerte                    Country = "105" // Isla de Muerte
	CountryPirates                         Country = "107" // Pirates
	CountryTaiwan                          Country = "108" // 台灣, 中國
	CountryHongKong                        Country = "109" // 香港, 中國
	CountryMacau                           Country = "110" // 澳門, 中國
	CountryFrenchPolynesia                 Country = "111" // French Polynesia
	CountryIran                            Country = "112" // Iran
	CountryIraq                            Country = "113" // Iraq
	CountryKazakhstan                      Country = "114" // Kazakhstan
	CountryPalau                           Country = "115" // Palau
	CountrySaudiArabia                     Country = "116" // Saudi Arabia
	CountrySovietUnion                     Country = "117" // Soviet Union
	CountryRepublikIndonesia               Country = "118" // Republik Indonesia
	CountryMalta                           Country = "119" // Malta
	CountryBotswana                        Country = "120" // Botswana
	CountryKenya                           Country = "121" // Kenya
	CountryGhana                           Country = "122" // Ghana
	CountryCzechoslovakia                  Country = "123" // Czechoslovakia
	CountryEswatini                        Country = "124" // Eswatini
	CountryQatar                           Country = "125" // Qatar
	CountryPakistan_126                    Country = "126" // Pakistan
	CountryNiger                           Country = "127" // Niger
	CountryCameroon                        Country = "128" // Cameroon
	CountryZambia                          Country = "129" // Zambia
	CountrySaintKittsAndNevis              Country = "130" // Saint Kitts and Nevis
	CountryMorocco                         Country = "131" // Morocco
	CountryLiechtenstein                   Country = "132" // Liechtenstein
	CountryJordan                          Country = "133" // Jordan
	CountryBahrain                         Country = "134" // bahrain
	CountrySlovakia                        Country = "135" // Slovakia
	CountryBelarus                         Country = "136" // Belarus
	CountryLiberia                         Country = "137" // Liberia
	CountryMonaco                          Country = "138" // Monaco
	CountryNorthMacedonia                  Country = "139" // North Macedonia
	CountrySriLanka                        Country = "140" // Sri Lanka
	CountryPalestinianTerritories          Country = "142" // Palestinian territories
	CountryTunisia                         Country = "143" // Tunisia
	CountryPanama                          Country = "144" // Panama
	CountryGeorgia                         Country = "145" // Georgia
	CountryKuwait                          Country = "146" // Kuwait
	CountryMongolia                        Country = "147" // Mongolia
	CountryLibya                           Country = "148" // Libya
	CountryMadagascar                      Country = "149" // Madagascar
	CountryNamibia                         Country = "150" // Namibia
	CountryIsleOfMan                       Country = "151" // Isle of Man
	CountryKosovo                          Country = "152" // Kosovo
	CountryCyprus                          Country = "153" // Cyprus
	CountryAruba                           Country = "154" // Aruba
	CountryBhutan                          Country = "155" // Bhutan
	CountryMicronesia                      Country = "156" // Micronesia
	CountryArmenia                         Country = "157" // Armenia
	CountryVatican                         Country = "158" // Vatican
	CountryAzerbaijan                      Country = "159" // Azerbaijan
	CountryPapuaNewGuinea                  Country = "160" // Papua New Guinea
	CountryMauritania                      Country = "161" // Mauritania
	CountryNepal                           Country = "162" // Nepal
	CountryMalawi                          Country = "163" // Malawi
	CountryHaiti                           Country = "164" // Haiti
	CountryGambia                          Country = "165" // Gambia
	CountryAntarctica                      Country = "166" // Antarctica
	CountryZimbabwe                        Country = "167" // Zimbabwe
	CountryMaldives                        Country = "168" // Maldives
	CountrySyria                           Country = "169" // Syria
	CountryMyanmar                         Country = "170" // Myanmar
	CountryLesotho                         Country = "171" // Lesotho
	CountryAngola_172                      Country = "172" // Angola
	CountryBolivia                         Country = "173" // Bolivia
)
